'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const { PGlite }=require('@electric-sql/pglite');
const licensing=require('../server/cpa-licensing');
const migration=fs.readFileSync(path.join(__dirname,'..','supabase/migrations/20260929_cpa_licenses.sql'),'utf8');

async function database(){const db=new PGlite();await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth; create schema extensions; create function extensions.gen_random_uuid() returns uuid language sql volatile as $$select gen_random_uuid()$$; create table auth.users(id uuid primary key default extensions.gen_random_uuid(),email text unique); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; create function auth.role() returns text language sql stable as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$; create function public.paxinbot_is_owner() returns boolean language sql stable as $$select current_setting('request.jwt.claim.owner',true)='true'$$;`);await db.exec(migration);return db;}
const env={CPA_LICENSE_HMAC_PEPPERS:JSON.stringify({v1:'pglite-security-matrix-pepper-longer-than-32'}),CPA_LICENSE_HMAC_CURRENT_VERSION:'v1'};
async function owner(db){const id=crypto.randomUUID();await db.query(`insert into auth.users(id,email) values($1,$2)`,[id,`owner-${id}@example.test`]);await db.query(`select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.owner','true',false),set_config('request.jwt.claim.role','authenticated',false)`,[id]);return id;}
async function key(db,unit='days',value=1,policy='first',custom=null){const k=licensing.generateLicense(env);const q=await db.query(`select public.cpa_owner_create_license($1,$2,$3,$4,$5,$6,$7,$8,null) data`,[k.keyId,k.keyPrefix,k.keyHash,k.pepperVersion,unit,value,custom,policy]);return {k,id:q.rows[0].data.id};}
async function service(db){await db.query(`select set_config('request.jwt.claim.role','service_role',false),set_config('request.jwt.claim.owner','',false)`);}
async function activate(db,item,hwid='a'.repeat(64),pub='A'.repeat(64),pubHash='b'.repeat(64),token='c'.repeat(64)){return db.query(`select public.cpa_license_activate($1::jsonb,$2,$3,$4,'cash-hunters-1.6.0-test',$5) data`,[JSON.stringify([{version:item.k.pepperVersion,hash:item.k.keyHash}]),hwid,pub,pubHash,token]);}

test('license lifecycle matrix rejects invalid states, mismatches and replay',async()=>{const db=await database();try{await owner(db);const first=await key(db,'days',1,'first');await service(db);const started=await activate(db,first);assert.equal(started.rows[0].data.licenseId,first.id);await assert.rejects(activate(db,first,'d'.repeat(64),'D'.repeat(64),'e'.repeat(64),'f'.repeat(64)),/hwid_mismatch/);await assert.rejects(db.query(`select public.cpa_license_refresh($1,$2,$3,$4,'cash-hunters-1.6.0-test')`,['c'.repeat(64),'d'.repeat(64),'d'.repeat(64),'e'.repeat(64)]),/hwid_mismatch|session_expired/);await db.query(`select set_config('request.jwt.claim.role','authenticated',false),set_config('request.jwt.claim.owner','true',false)`);await db.query(`select public.cpa_owner_update_license($1,'reset_device')`,[first.id]);await service(db);await assert.rejects(db.query(`select public.cpa_license_refresh($1,$2,$3,$4,'cash-hunters-1.6.0-test')`,['c'.repeat(64),'d'.repeat(64),'a'.repeat(64),'b'.repeat(64)]),/session_expired|hwid_mismatch/);const replay=crypto.randomUUID();await db.query(`select public.cpa_license_create_challenge($1,'activate','${'a'.repeat(64)}','${'n'.repeat(43)}')`,[replay]);const consumed=await db.query(`select public.cpa_license_consume_challenge($1) data`,[replay]);assert.equal(consumed.rows[0].data.status,'ready');const again=await db.query(`select public.cpa_license_consume_challenge($1) data`,[replay]);assert.equal(again.rows[0].data.status,'replay');}finally{await db.close();}});

test('immediate custom, lifetime, expiry and calendar month semantics',async()=>{const db=await database();try{await owner(db);const immediate=await key(db,'custom',null,'immediate',new Date(Date.now()+86400000).toISOString());const life=await key(db,'lifetime',null,'immediate');await service(db);assert.ok((await db.query(`select public.cpa_license_activate($1::jsonb,$2,$3,$4,'cash-hunters-test',$5) data`,[JSON.stringify([{version:immediate.k.pepperVersion,hash:immediate.k.keyHash}]),'1'.repeat(64),'B'.repeat(64),'2'.repeat(64),'3'.repeat(64)])).rows[0].data.licenseExpiresAt);const lifetime=await activate(db,life,'4'.repeat(64),'C'.repeat(64),'5'.repeat(64),'6'.repeat(64));assert.equal(lifetime.rows[0].data.licenseExpiresAt,null);const month=await db.query(`select public.cpa_license_expiry('months',1,null,'2027-01-31T12:00:00Z') value`);assert.equal(new Date(month.rows[0].value).toISOString(),'2027-02-28T12:00:00.000Z');}finally{await db.close();}});

test('suspended revoked banned expired and device bans deny authorization',async()=>{const db=await database();try{await owner(db);for(const operation of ['suspend','revoke','ban']){await db.query("select set_config('request.jwt.claim.owner','true',false)");const item=await key(db);await service(db);await activate(db,item,'7'.repeat(64),'D'.repeat(64),'8'.repeat(64),crypto.randomBytes(32).toString('hex'));await db.query(`select set_config('request.jwt.claim.role','authenticated',false),set_config('request.jwt.claim.owner','true',false)`);await db.query(`select public.cpa_owner_update_license($1,$2)`,[item.id,operation]);await service(db);await assert.rejects(activate(db,item,'7'.repeat(64),'D'.repeat(64),'8'.repeat(64),crypto.randomBytes(32).toString('hex')),new RegExp(operation));}await db.query("select set_config('request.jwt.claim.owner','true',false)");const expired=await key(db,'custom',null,'immediate',new Date(Date.now()-1000).toISOString()).catch(e=>e);assert.ok(expired instanceof Error);const device=await key(db);await service(db);await activate(db,device,'e'.repeat(64),'E'.repeat(64),'f'.repeat(64),'1'.repeat(64));await db.query(`select set_config('request.jwt.claim.role','authenticated',false),set_config('request.jwt.claim.owner','true',false)`);await db.query(`select public.cpa_owner_set_device_ban($1,true)`,['e'.repeat(64)]);await service(db);await assert.rejects(activate(db,device,'e'.repeat(64),'E'.repeat(64),'f'.repeat(64),'2'.repeat(64)),/device_banned/);}finally{await db.close();}});

test('owner boundary, SQL-shaped input and pending deactivation cannot self activate',async()=>{const db=await database();try{const ownerId=await owner(db);const item=await key(db);await db.query(`select set_config('request.jwt.claim.owner','false',false)`);await assert.rejects(db.query(`select public.cpa_owner_list_licenses($1,'',200)`,[`' or 1=1 --`]),/owner_required|permission denied/);await db.query(`select set_config('request.jwt.claim.owner','true',false)`);await db.query(`select public.cpa_owner_update_license($1,'deactivate')`,[item.id]);await service(db);await assert.rejects(activate(db,item,'a'.repeat(64),'A'.repeat(64),'b'.repeat(64),'c'.repeat(64)),/invalid_key/);await db.query(`set role anon`);await assert.rejects(db.query(`select public.cpa_owner_list_licenses('',null,200)`),/permission denied/);await db.query(`reset role`);assert.ok(ownerId);}finally{await db.close();}});

test('admin duration updates honor calendar expiry and pending activation policy',async()=>{const db=await database();try{await owner(db);const pending=await key(db,'days',1,'first');await db.query(`select public.cpa_owner_update_license($1,'activate')`,[pending.id]);let row=await db.query(`select status,duration_unit,expires_at from public.cpa_licenses where id=$1`,[pending.id]);assert.equal(row.rows[0].status,'active');assert.equal(row.rows[0].duration_unit,'days');await db.query(`select public.cpa_owner_update_license($1,'extend','months',1,null,null)`,[pending.id]);row=await db.query(`select duration_unit,expires_at from public.cpa_licenses where id=$1`,[pending.id]);assert.equal(row.rows[0].duration_unit,'months');assert.ok(row.rows[0].expires_at);await db.query(`select public.cpa_owner_update_license($1,'set_expiration',null,null,$2)`,[pending.id,'2030-02-28T00:00:00Z']);row=await db.query(`select duration_unit,expires_at from public.cpa_licenses where id=$1`,[pending.id]);assert.equal(row.rows[0].duration_unit,'custom');assert.equal(new Date(row.rows[0].expires_at).toISOString(),'2030-02-28T00:00:00.000Z');const lifetime=await key(db,'lifetime',null,'immediate');await db.query(`select public.cpa_owner_update_license($1,'set_expiration',null,null,null)`,[lifetime.id]);row=await db.query(`select duration_unit,expires_at from public.cpa_licenses where id=$1`,[lifetime.id]);assert.equal(row.rows[0].duration_unit,'lifetime');assert.equal(row.rows[0].expires_at,null);}finally{await db.close();}});

test('reset device permits a new binding while the old session stays unusable',async()=>{const db=await database();try{await owner(db);const item=await key(db);await service(db);await activate(db,item,'a'.repeat(64),'A'.repeat(64),'b'.repeat(64),'c'.repeat(64));await db.query(`select set_config('request.jwt.claim.role','authenticated',false),set_config('request.jwt.claim.owner','true',false)`);await db.query(`select public.cpa_owner_update_license($1,'reset_device')`,[item.id]);await service(db);const next=await activate(db,item,'d'.repeat(64),'D'.repeat(64),'e'.repeat(64),'f'.repeat(64));assert.equal(next.rows[0].data.licenseId,item.id);await assert.rejects(db.query(`select public.cpa_license_refresh($1,$2,$3,$4,'cash-hunters-1.6.0-test')`,['c'.repeat(64),'1'.repeat(64),'a'.repeat(64),'b'.repeat(64)]),/invalid_request|session_expired|hwid_mismatch/);}finally{await db.close();}});

test('null service claims and direct data reads remain denied after migration reapply',async()=>{const db=await database();try{await db.exec(migration);await owner(db);const item=await key(db);await db.query(`select set_config('request.jwt.claim.role','',false)`);await assert.rejects(activate(db,item),/service_role_required|permission denied/);await db.query(`set role authenticated`);await assert.rejects(db.query(`select * from public.cpa_licenses`),/permission denied/);await db.query(`reset role`);await db.query(`set role anon`);await assert.rejects(db.query(`select * from public.cpa_sessions`),/permission denied/);await db.query(`reset role`);}finally{await db.close();}});
